### ISSUE TITLE
FuckAdBlock and BlockAdBlock vs uBlock

### ISSUE THREAD

**Issue by DSBalaban** [sitexw/BlockAdBlock#20]
I understand that they're supposed to be the same, but FuckAdBlock works against uBlock, BlockAdBlock does not (according to the demo).

![screen shot 2017-03-02 at 14 47 41](https://cloud.githubusercontent.com/assets/9392041/23507789/52f82258-ff57-11e6-9462-6422ab6bf9bb.png)

![screen shot 2017-03-02 at 14 47 57](https://cloud.githubusercontent.com/assets/9392041/23507796/56b68a42-ff57-11e6-9af5-c8a5872148ea.png)

**EDIT:** I just noticed FuckAdBlock was running Beta V4.

**Comment by sitexw** [comment]
Indeed, it is a mistake on my part, because I omitted the attribute "integrity" ([Subresource Integrity](https://developer.mozilla.org/fr/docs/Web/Security/Subresource_Integrity)).
And since uBlock is smarter than AdBlock, it corrupts the script by replacing it with a harmless version of BlockAdBlock.
I will update the documentation and talk a bit more about this very effective protection system. It is already highlighted on the [V4](https://github.com/sitexw/FuckAdBlock/tree/v4.x).

You can go see, now everything is back in order thanks to "integrity" :
- https://fuckadblock.sitexw.fr/
- https://fuckadblock.sitexw.fr/blockadblock/
- https://fuckadblock.sitexw.fr/beta/

**Comment by DSBalaban** [comment]
Integrity's quite effective indeed. Too bad browser support is rather limited for now.

Thanks for the quick response. I'll go ahead and close since it's resolved.

**Comment by sitexw** [comment]
Indeed, the compatibility is not optimal yet, the other browsers begin to think about it (Edge and Safari).
Otherwise, in addition to integrity, you can simply count the number of characters in the class BlockAdBlock (because uBlock is completely different):
```javascript
if(BlockAdBlock.toString().length === 1212) {
	console.log('Real BlockAdBlock');
} else {
	console.log('Fake BlockAdBlock');
}
```
_(uBlock to 14 characters...)_
